# Generated by Django 4.1.1 on 2022-09-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanlist',
            old_name='interest_rate',
            new_name='interestrate',
        ),
        migrations.RenameField(
            model_name='loanlist',
            old_name='loan_amount',
            new_name='loanamount',
        ),
        migrations.RenameField(
            model_name='loanlist',
            old_name='loan_term',
            new_name='loanterm',
        ),
        migrations.AddConstraint(
            model_name='loanlist',
            constraint=models.CheckConstraint(check=models.Q(('loanamount__gte', 1000), ('loanamount__lt', 100000000)), name='Loan_amount_is_valid_between_1000_and_100,000,000_THB'),
        ),
    ]
