# Generated by Django 4.1.1 on 2022-09-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_rename_interest_rate_loanlist_interestrate_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='loanlist',
            name='Loan_amount_is_valid_between_1000_and_100,000,000_THB',
        ),
        migrations.RenameField(
            model_name='loanlist',
            old_name='interestrate',
            new_name='interest_rate',
        ),
        migrations.RenameField(
            model_name='loanlist',
            old_name='loanamount',
            new_name='loan_amount',
        ),
        migrations.RenameField(
            model_name='loanlist',
            old_name='loanterm',
            new_name='loan_term',
        ),
        migrations.AddConstraint(
            model_name='loanlist',
            constraint=models.CheckConstraint(check=models.Q(('loan_amount__gte', 1000), ('loan_amount__lt', 100000000)), name='Loan amount is valid between 1000 and 100,000,000 THB'),
        ),
    ]
