# Generated by Django 4.1.1 on 2022-09-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_remove_loanlist_loan_amount_is_valid_between_1000_and_100,000,000_thb_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='loanlist',
            constraint=models.CheckConstraint(check=models.Q(('loan_term__gte', 1), ('loan_term__lt', 50)), name='Loan term is valid between 1 and 50 years'),
        ),
    ]
