# Generated by Django 4.1.1 on 2022-09-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loanlist_loan term is valid between 1 and 50 years'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='loanlist',
            name='Loan amount is valid between 1000 and 100,000,000 THB',
        ),
        migrations.RemoveConstraint(
            model_name='loanlist',
            name='Loan term is valid between 1 and 50 years',
        ),
        migrations.AddConstraint(
            model_name='loanlist',
            constraint=models.CheckConstraint(check=models.Q(('loan_amount__gte', 1000), ('loan_amount__lte', 100000000)), name='Loan amount is valid between 1000 and 100,000,000 THB'),
        ),
        migrations.AddConstraint(
            model_name='loanlist',
            constraint=models.CheckConstraint(check=models.Q(('loan_term__gte', 1), ('loan_term__lte', 50)), name='Loan term is valid between 1 and 50 years'),
        ),
    ]
